CI : full matrix
Signed-off-by: entlein <einentlein@gmail.com>

diff --git a/.github/workflows/ci-redis-bob-kernel-k0sk3s.yaml b/.github/workflows/ci-redis-bob-kernel-k0sk3s.yaml
--- a/.github/workflows/ci-redis-bob-kernel-k0sk3s.yaml
+++ b/.github/workflows/ci-redis-bob-kernel-k0sk3s.yaml
@@ -13,9 +13,9 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        os: [ubuntu-22.04] # ubuntu-24.04]
+        os: [ubuntu-22.04 ,ubuntu-24.04]
         k8s-distribution: [k3s, kind]  #fix k0s
-        kubernetes-version: [v1.27.3] #,  v1.29.0, v1.30.0, v1.31.0] # we already tested v1.32.0 and for some reason k3s download of v1.28.0 fails
+        kubernetes-version: [v1.27.3, v1.29.0, v1.30.0, v1.31.0] # we already tested v1.32.0 and for some reason k3s download of v1.28.0 fails
     runs-on: ${{ matrix.os }}
 
 
@@ -85,20 +85,49 @@ jobs:
           fi
           kubectl logs -l app=node-agent -n honey | grep  "Unexpected" > /tmp/anomalyobserved.json
           jq -r '.BaseRuntimeMetadata.alertName' /tmp/anomalyobserved.json | sort > /tmp/actual_alerts.txt
-          jq -r '.BaseRuntimeMetadata.alertName' ./testdata/kind/redis_attack_raw.json | sort > /tmp/expected_alerts.txt
+          jq -r '.BaseRuntimeMetadata.alertName' ./testdata/redis_attack_raw.json | sort > /tmp/expected_alerts.txt
           if ! diff -u /tmp/expected_alerts.txt /tmp/actual_alerts.txt; then
             echo "❌ Alert names do not match expected!"
           fi
 
-
-      - name: Run Supply Chain SwitchOut (change redis image but not bob)
+      - name: Compare alertName and first argument with expected anomalies
         run: |
-          make helm-redis-compromise
-          echo "Checking for unexpected anomalies in Kubescape logs..."
-          kubectl get applicationprofile -n bob -o yaml
-          sleep 25
-          kubectl get statefulset -n bob -o jsonpath='{.items[0].status.currentRevision}'|cut -f4 -d '-'
-          kubectl logs -n honey -l app=node-agent 
+          kubectl logs -l app=node-agent -n honey | grep  "Unexpected" > /tmp/anomalyobserved.json
+          extract() {
+            jq -r '
+              [
+                .BaseRuntimeMetadata.alertName,
+                (
+                  .BaseRuntimeMetadata.arguments.flags[0] // 
+                  .BaseRuntimeMetadata.arguments.args[0] // 
+                  .BaseRuntimeMetadata.arguments.addresses[0] // 
+                  .BaseRuntimeMetadata.arguments.syscall // 
+                  ""
+                )
+              ] | @tsv
+            ' "$1" | sort
+          }
+
+
+          extract /tmp/anomalyobserved.json > /tmp/actual_alerts.tsv
+          extract ./testdata/redis_attack_raw.json > /tmp/expected_alerts.tsv
+          echo "Actual:"
+          cat /tmp/actual_alerts.tsv
+          echo "Expected:"
+          cat /tmp/expected_alerts.tsv
+
+          # Compare
+          if ! diff -u /tmp/expected_alerts.tsv /tmp/actual_alerts.tsv; then
+            echo "❌ alertName/first-argument pairs do not match expected!"
+          fi
+      # - name: Run Supply Chain SwitchOut (change redis image but not bob)
+      #   run: |
+      #     make helm-redis-compromise
+      #     echo "Checking for unexpected anomalies in Kubescape logs..."
+      #     kubectl get applicationprofile -n bob -o yaml
+      #     sleep 25
+      #     kubectl get statefulset -n bob -o jsonpath='{.items[0].status.currentRevision}'|cut -f4 -d '-'
+      #     kubectl logs -n honey -l app=node-agent 
 
 
 
